name: Docker build
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/buildx-latest.yml
      - .github/workflows/buildx-release.yml
      - .github/workflows/dockerhub-description.yml
      - .github/workflows/labels.yml
      - .github/CODEOWNERS
      - .github/CONTRIBUTING.md
      - .github/FUNDING.yml
      - .github/labels.yml
      - .vscode
      - .gitignore
      - docker-compose.yml
      - LICENSE
      - README.md
      - title.svg
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build web frontend
        run: docker buildx build -o build ui
      - name: Build image
        run: docker build .
